apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --out k8s/services/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: circulation-db
  name: circulation-db
spec:
  ports:
    - name: "7434"
      port: 7434
      targetPort: 5432
  selector:
    io.kompose.service: circulation-db
status:
  loadBalancer: {}
