apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --out k8s/services/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: members-db
  name: members-db
spec:
  ports:
    - name: "7435"
      port: 7435
      targetPort: 5432
  selector:
    io.kompose.service: members-db
status:
  loadBalancer: {}
