apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: catalog-db
  name: catalog-db
spec:
  ports:
    - name: "7433"
      port: 7433
      targetPort: 5432
  selector:
    io.kompose.service: catalog-db
status:
  loadBalancer: {}
